name: BE CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./be

jobs:
  ci:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - run: go mod download
        env:
          GOPROXY: "https://proxy.golang.org"
      - run: go test ./...
        env:
          GOPROXY: "https://proxy.golang.org"
